name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
      - name: Build Flutter Web - Prod
        run:
          flutter config --enable-web &&
          flutter pub get &&
          flutter build web --release --web-renderer canvaskit
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RICARDOWORKOUTPLANNER }}'
          channelId: live
          projectId: ricardoworkoutplanner
